// action - canvas reducer
export const SET_DIRTY = 'SET_DIRTY';
export const REMOVE_DIRTY = 'REMOVE_DIRTY';
export const SET_CHATFLOW = 'SET_CHATFLOW';
export const SHOW_CANVAS_DIALOG = 'SHOW_CANVAS_DIALOG';
export const HIDE_CANVAS_DIALOG = 'HIDE_CANVAS_DIALOG';
export const SET_COMPONENT_NODES = 'SET_COMPONENT_NODES';
export const SET_COMPONENT_CREDENTIALS = 'SET_COMPONENT_CREDENTIALS';

export const HIDE_CONFIRM = 'HIDE_CONFIRM';
export const SHOW_CONFIRM = 'SHOW_CONFIRM';